### ISSUE TITLE
IDEA 快捷键格式化代码后代码显示问题

### ISSUE THREAD

**Issue by 24Arise** [twtyjvkg/aurora-support#6]
screen页面中若有```<style>```标签，使用快捷键格式化代码后会出现代码显示问题，而```<javascript>```标签则没有这一问题。如下图：
![image](https://user-images.githubusercontent.com/8738126/53155905-11024100-35f9-11e9-98af-d128b1a33185.png)

**Comment by twtyjvkg** [comment]
这个是xhtml的校验，它不允许在style里添加CDATA，还没找到解决办法
